//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cyclesrender.rc
//
#define IDS_CYCLES_UNIFIED_RENDERER     1
#define IDS_PARAMS                      2
#define IDS_NORMAL_PARAMS               3
#define IDC_BUTTON_DEVICE_ALL           3
#define IDS_TRANSPARENT_SKY             4
#define IDC_BUTTON_DEVICE_SINGLE        4
#define IDS_DENSITY                     5
#define IDS_DUMMY                       6
#define IDS_ENABLE_NORMAL_MAP           7
#define IDS_INVERT_GREEN                8
#define IDS_BLEND_MODE                  9
#define IDS_CLIPPING                    10
#define IDS_MIN_LATTITUDE               11
#define IDS_MAX_LATTITUDE               12
#define IDS_MIN_LONGITUDE               13
#define IDS_MAX_LONGITUDE               14
#define IDS_FOV                         15
#define IDS_FOCAL_LENGTH                16
#define IDS_SENSOR_SIZE                 17
#define IDS_STEREOSCOPY                 18
#define IDS_CC_NORMAL_PARAMS            19
#define IDS_GENERAL                     20
#define IDS_SHADER_PARAMS               21
#define IDS_VOLUME_SAMPLING             22
#define IDS_VOLUME_INTERP               23
#define IDS_VOLUME_HOMOGENEOUS          24
#define IDS_SURFACE_MIS                 25
#define IDS_STRING26                    26
#define IDS_IGNORE_ORIGINAL_PBLOCK      26
#define IDS_DISPLACEMENT_BUMP           27
#define IDS_DISPLACEMENT                27
#define IDS_WIDTH                       100
#define IDS_HEIGHT                      101
#define IDS_SUN_VEC_X                   102
#define IDS_SUN_VEC_Y                   103
#define IDS_SUN_VEC_Z                   104
#define IDS_TURBIDITY                   105
#define IDS_GROUND_ALBEDO               106
#define IDS_PROJECTION                  107
#define IDS_USE_MIS                     108
#define IDS_ROUGHNESS                   109
#define IDS_FALLOFF                     110
#define IDS_IOR                         111
#define IDS_COMPONENT                   112
#define IDS_DISTRIBUTION                113
#define IDS_PRECISION                   114
#define IDS_SKY_TYPE                    115
#define IDS_RADIUS_X                    116
#define IDS_RADIUS_Y                    117
#define IDS_RADIUS_Z                    118
#define IDS_STRENGTH                    119
#define IDS_COLOR                       120
#define IDS_FAC                         121
#define IDS_ANISOTROPY                  122
#define IDS_ROTATION                    123
#define IDS_SIZE                        124
#define IDS_SMOOTH                      125
#define IDS_SIGMA                       126
#define IDS_SCALE                       127
#define IDS_SHARPNESS                   128
#define IDS_TEX_BLUR                    129
#define IDS_OFFSET                      130
#define IDS_ROUGHNESS_U                 131
#define IDS_ROUGHNESS_V                 132
#define IDS_REFL_PROJECTION             133
#define IDS_SPACE                       134
#define IDS_NEARCLIP                    135
#define IDS_FARCLIP                     136
#define IDS_PANORAMA_TYPE               137
#define IDS_METALLIC                    138
#define IDS_SHEEN                       139
#define IDS_SHEEN_TINT                  140
#define IDS_TRANSMISSION                141
#define IDS_TRANSMISSION_ROUGHNESS      142
#define IDS_SPECULAR                    143
#define IDS_SPECULAR_TINT               144
#define IDS_ANISOTROPIC                 145
#define IDS_ANISOTROPIC_ROTATION        146
#define IDS_SUBSURFACE                  147
#define IDS_SUBSURFACE_COLOR            148
#define IDS_CLEARCOAT                   149
#define IDS_CLEARCOAT_ROUGHNESS         150
#define IDS_SHADOW_CATCHER              151
#define IDS_SUBSURFACE_METHOD           152
#define IDS_EMISSION                    153
#define IDS_ALPHA                       154
#define IDS_MATERIAL_A                  200
#define IDS_MATERIAL_B                  201
#define IDS_SURFACE_MATERIAL            202
#define IDS_VIEWPORT_MATERIAL           203
#define IDS_VOLUME_MATERIAL             204
#define IDS_BACKGROUND_MAP              300
#define IDS_BACKGROUND_MAP_ENABLED      301
#define IDS_TEXMAP                      302
#define IDS_TEXMAP_ENABLED              303
#define IDS_STRENGTH_TEXMAP             304
#define IDS_STRENGTH_TEXMAP_ENABLED     305
#define IDS_COLOR_TEXMAP                306
#define IDS_COLOR_TEXMAP_ENABLED        307
#define IDS_ROUGHNESS_TEXMAP            308
#define IDS_ROUGHNESS_TEXMAP_ENABLED    309
#define IDS_FAC_TEXMAP                  310
#define IDS_FAC_TEXMAP_ENABLED          311
#define IDS_ANISOTROPY_TEXMAP           312
#define IDS_ANISOTROPY_TEXMAP_ENABLED   313
#define IDS_ROTATION_TEXMAP             314
#define IDS_ROTATION_TEXMAP_ENABLED     315
#define IDS_SIZE_TEXMAP                 316
#define IDS_SIZE_TEXMAP_ENABLED         317
#define IDS_SMOOTH_TEXMAP               318
#define IDS_SMOOTH_TEXMAP_ENABLED       319
#define IDS_SIGMA_TEXMAP                320
#define IDS_SIGMA_TEXMAP_ENABLED        321
#define IDS_SCALE_TEXMAP                322
#define IDS_SCALE_TEXMAP_ENABLED        323
#define IDS_SHARPNESS_TEXMAP            324
#define IDS_SHARPNESS_TEXMAP_ENABLED    325
#define IDS_TEX_BLUR_TEXMAP             326
#define IDS_TEX_BLUR_TEXMAP_ENABLED     327
#define IDS_OFFSET_TEXMAP               328
#define IDS_OFFSET_TEXMAP_ENABLED       329
#define IDS_ROUGHNESS_U_TEXMAP          330
#define IDS_ROUGHNESS_U_TEXMAP_ENABLED  331
#define IDS_ROUGHNESS_V_TEXMAP          332
#define IDS_ROUGHNESS_V_TEXMAP_ENABLED  333
#define IDS_LIGHTING_MAP                334
#define IDS_LIGHTING_MAP_ENABLED        335
#define IDS_METALLIC_TEXMAP             336
#define IDS_METALLIC_TEXMAP_ENABLED     337
#define IDS_SHEEN_TEXMAP                338
#define IDS_SHEEN_TEXMAP_ENABLED        339
#define IDS_SHEEN_TINT_TEXMAP           340
#define IDS_SHEEN_TINT_TEXMAP_ENABLED   341
#define IDS_TRANSMISSION_TEXMAP         342
#define IDS_TRANSMISSION_TEXMAP_ENABLED 343
#define IDS_TRANSMISSION_ROUGHNESS_TEXMAP 344
#define IDS_TRANSMISSION_ROUGHNESS_TEXMAP_ENABLED 345
#define IDS_SPECULAR_TEXMAP             346
#define IDS_SPECULAR_TEXMAP_ENABLED     347
#define IDS_SPECULAR_TINT_TEXMAP        348
#define IDS_SPECULAR_TINT_TEXMAP_ENABLED 349
#define IDS_ANISOTROPIC_TEXMAP          350
#define IDS_ANISOTROPIC_TEXMAP_ENABLED  351
#define IDS_ANISOTROPIC_ROTATION_TEXMAP 352
#define IDS_ANISOTROPIC_ROTATION_TEXMAP_ENABLED 353
#define IDS_SUBSURFACE_TEXMAP           354
#define IDS_SUBSURFACE_TEXMAP_ENABLED   355
#define IDS_SUBSURFACE_COLOR_TEXMAP     356
#define IDS_SUBSURFACE_COLOR_TEXMAP_ENABLED 357
#define IDS_CLEARCOAT_TEXMAP            358
#define IDS_CLEARCOAT_TEXMAP_ENABLED    359
#define IDS_CLEARCOAT_ROUGHNESS_TEXMAP  360
#define IDS_CLEARCOAT_ROUGHNESS_TEXMAP_ENABLED 361
#define IDS_EMISSION_TEXMAP             362
#define IDS_EMISSION_TEXMAP_ENABLED     363
#define IDS_ALPHA_TEXMAP                364
#define IDS_ALPHA_TEXMAP_ENABLED        365
#define IDS_NORMAL_TEXMAP               390
#define IDS_NORMAL_TEXMAP_ENABLED       391
#define IDS_TEXMAP_01                   400
#define IDS_TEXMAP_01_ENABLED           401
#define IDS_TEXMAP_02                   402
#define IDS_TEXMAP_02_ENABLED           403
#define IDS_TEXMAP_03                   404
#define IDS_TEXMAP_03_ENABLED           405
#define IDS_TEXMAP_04                   406
#define IDS_TEXMAP_04_ENABLED           407
#define IDS_TEXMAP_05                   408
#define IDS_TEXMAP_05_ENABLED           409
#define IDS_TEXMAP_06                   410
#define IDS_TEXMAP_06_ENABLED           411
#define IDS_TEXMAP_07                   412
#define IDS_TEXMAP_07_ENABLED           413
#define IDS_TEXMAP_08                   414
#define IDS_TEXMAP_08_ENABLED           415
#define IDS_TEXMAP_09                   416
#define IDS_TEXMAP_09_ENABLED           417
#define IDS_TEXMAP_10                   418
#define IDS_TEXMAP_10_ENABLED           419
#define IDS_TEXMAP_11                   420
#define IDS_TEXMAP_11_ENABLED           421
#define IDS_TEXMAP_12                   422
#define IDS_TEXMAP_12_ENABLED           423
#define IDS_TEXMAP_13                   424
#define IDS_TEXMAP_13_ENABLED           425
#define IDS_TEXMAP_14                   426
#define IDS_TEXMAP_14_ENABLED           427
#define IDS_TEXMAP_15                   428
#define IDS_TEXMAP_15_ENABLED           429
#define IDS_TEXMAP_16                   430
#define IDS_TEXMAP_16_ENABLED           431
#define IDS_TEXMAP_17                   432
#define IDS_TEXMAP_17_ENABLED           433
#define IDS_TEXMAP_18                   434
#define IDS_TEXMAP_18_ENABLED           435
#define IDS_TEXMAP_19                   436
#define IDS_TEXMAP_19_ENABLED           437
#define IDS_TEXMAP_20                   438
#define IDS_TEXMAP_20_ENABLED           439
#define IDS_TEXMAP_21                   440
#define IDS_TEXMAP_21_ENABLED           441
#define IDS_TEXMAP_22                   442
#define IDS_TEXMAP_22_ENABLED           443
#define IDS_TEXMAP_23                   444
#define IDS_TEXMAP_23_ENABLED           445
#define IDS_TEXMAP_24                   446
#define IDS_TEXMAP_24_ENABLED           447
#define IDS_TEXMAP_25                   448
#define IDS_TEXMAP_25_ENABLED           449
#define IDS_TEXMAP_26                   450
#define IDS_TEXMAP_26_ENABLED           451
#define IDS_TEXMAP_27                   452
#define IDS_TEXMAP_27_ENABLED           453
#define IDS_TEXMAP_28                   454
#define IDS_TEXMAP_28_ENABLED           455
#define IDS_TEXMAP_29                   456
#define IDS_TEXMAP_29_ENABLED           457
#define IDS_TEXMAP_30                   458
#define IDS_TEXMAP_30_ENABLED           459
#define IDS_TEXMAP_31                   460
#define IDS_TEXMAP_31_ENABLED           461
#define IDS_TEXMAP_32                   462
#define IDS_TEXMAP_32_ENABLED           463
#define IDS_USE_SPHERICAL_STEREO        500
#define IDS_USE_POLE_MERGE              501
#define IDS_POLE_MERGE_FROM             502
#define IDS_POLE_MERGE_TO               503
#define IDS_RE_ENABLED                  600
#define IDS_RE_FILTER_ENABLED           601
#define IDS_RE_NAME                     602
#define IDS_RE_BITMAP                   603
#define IDD_PANEL_COMMON_NORMAL         800
#define IDD_PANEL_TEXMAP_FILTER         810
#define IDD_PANEL_TEXMAP_SKY            811
#define IDD_PANEL_TEXMAP_ENVIRONMENT    812
#define IDD_PANEL_MAT_EMISSION          840
#define IDD_PANEL_MAT_TRANSLUCENT       841
#define IDD_PANEL_MAT_MIX               842
#define IDD_PANEL_MAT_DIFFUSE           843
#define IDD_PANEL_MAT_GLOSSY            844
#define IDD_PANEL_MAT_GLASS             845
#define IDD_PANEL_MAT_TRANSPARENT       846
#define IDD_PANEL_MAT_ANISOTROPIC       847
#define IDD_PANEL_MAT_TOON              848
#define IDD_PANEL_MAT_REFRACTION        849
#define IDD_PANEL_MAT_VELVET            850
#define IDD_PANEL_MAT_SHADER            851
#define IDD_PANEL_MAT_HOLDOUT           852
#define IDD_PANEL_MAT_SUBSURFACE_SCATTER 853
#define IDD_PANEL_MAT_HAIR              854
#define IDD_PANEL_MAT_ADD               855
#define IDD_PANEL_MAT_VOL_SCATTER       856
#define IDD_PANEL_MAT_VOL_ABSORPTION    857
#define IDD_PANEL_MAT_PRINCIPLED        858
#define IDD_PANEL_MAT_SHADER_GRAPH      859
#define IDD_PANEL_MAT_SHADER_GRAPH_08_PARAMS 860
#define IDD_PANEL_MAT_SHADER_GRAPH_16_PARAMS 861
#define IDD_PANEL_MAT_SHADER_GRAPH_32_PARAMS 862
#define IDD_PANEL_MAT_SHADER_PARAMS     863
#define IDD_RENDER_CONFIG               900
#define IDD_RENDER_CONFIG_SAMPLING      901
#define IDD_RENDER_CONFIG_TRANSLATION   902
#define IDD_RENDER_CONFIG_LIGHT_PATH    903
#define IDD_RENDER_CONFIG_FILM          904
#define IDD_RENDER_CONFIG_PERF          905
#define IDD_RENDER_CONFIG_VERSION       906
#define IDD_RENDER_CONFIG_DEBUG         907
#define IDD_RENDER_PROG                 908
#define IDD_RENDER_CONFIG_STEREO        909
#define IDD_RENDER_CONFIG_PASSES        910
#define IDD_PANEL_CAM_PANO_PARAM        911
#define IDD_PANEL_CAM_PANO_CLIP         912
#define IDD_PANEL_CAM_PANO_STEREO       913
#define IDD_PANEL_MOD_PROPERTIES        914
#define IDD_PANEL_MAT_VOL_ADD           915
#define IDD_PANEL_MAT_VOL_MIX           916
#define IDC_SWATCH                      1000
#define IDC_SWATCH_SUBSURFACE           1001
#define IDC_SWATCH_EMISSION             1002
#define IDC_EDIT_BG_INTENSITY           1100
#define IDC_SPIN_BG_INTENSITY           1101
#define IDC_EDIT_SAMPLES                1102
#define IDC_SPIN_SAMPLES                1103
#define IDC_EDIT_MAT_PREVIEW_SAMPLES    1104
#define IDC_EDIT_VOL_STEP_RATE          1104
#define IDC_SPIN_MAT_PREVIEW_SAMPLES    1105
#define IDC_SPIN_VOL_STEP_RATE          1105
#define IDC_EDIT_WIDTH                  1106
#define IDC_EDIT_VOL_MAX_STEPS          1106
#define IDC_SPIN_WIDTH                  1107
#define IDC_SPIN_VOL_MAX_STEPS          1107
#define IDC_EDIT_HEIGHT                 1108
#define IDC_EDIT_ADAPTIVE_THRESHOLD     1108
#define IDC_SPIN_HEIGHT                 1109
#define IDC_SPIN_ADAPTIVE_THRESHOLD     1109
#define IDC_EDIT_CLAMP_DIRECT           1110
#define IDC_SPIN_CLAMP_DIRECT           1111
#define IDC_EDIT_CLAMP_INDIRECT         1112
#define IDC_SPIN_CLAMP_INDIRECT         1113
#define IDC_EDIT_ROUGHNESS              1114
#define IDC_EDIT_ADAPTIVE_MIN           1114
#define IDC_SPIN_ROUGHNESS              1115
#define IDC_SPIN_ADAPTIVE_MIN           1115
#define IDC_EDIT_RAND_SEED              1116
#define IDC_EDIT_MAX_LAT                1116
#define IDC_EDIT_SHEEN                  1116
#define IDC_SPIN_RAND_SEED              1117
#define IDC_SPIN_MAX_LAT                1117
#define IDC_SPIN_SHEEN                  1117
#define IDC_EDIT_FAC                    1118
#define IDC_EDIT_MAX_LONG               1118
#define IDC_EDIT_SHEEN_TINT             1118
#define IDC_SPIN_FAC                    1119
#define IDC_SPIN_MAX_LONG               1119
#define IDC_SPIN_SHEEN_TINT             1119
#define IDC_EDIT_IOR                    1120
#define IDC_EDIT_FOCAL_LENGTH           1120
#define IDC_SPIN_IOR                    1121
#define IDC_SPIN_FOCAL_LENGTH           1121
#define IDC_EDIT_ANISO                  1122
#define IDC_EDIT_SENSOR_SIZE            1122
#define IDC_EDIT_TRANSMISSION           1122
#define IDC_SPIN_ANISO                  1123
#define IDC_SPIN_SENSOR_SIZE            1123
#define IDC_SPIN_TRANSMISSION           1123
#define IDC_EDIT_STRENGTH               1124
#define IDC_EDIT_TRANSMISSION_ROUGHNESS 1124
#define IDC_SPIN_STRENGTH               1125
#define IDC_SPIN_TRANSMISSION_ROUGHNESS 1125
#define IDC_EDIT_ROT                    1126
#define IDC_EDIT_SPECULAR               1126
#define IDC_SPIN_ROT                    1127
#define IDC_SPIN_SPECULAR               1127
#define IDC_EDIT_SIZE                   1128
#define IDC_EDIT_SPECULAR_TINT          1128
#define IDC_SPIN_SIZE                   1129
#define IDC_SPIN_SPECULAR_TINT          1129
#define IDC_EDIT_SMOOTH                 1130
#define IDC_EDIT_ANISOTROPIC            1130
#define IDC_SPIN_SMOOTH                 1131
#define IDC_SPIN_ANISOTROPIC            1131
#define IDC_EDIT_SIGMA                  1132
#define IDC_EDIT_ANISOTROPIC_ROT        1132
#define IDC_SPIN_SIGMA                  1133
#define IDC_SPIN_ANISOTROPIC_ROT        1133
#define IDC_EDIT_TURB                   1134
#define IDC_EDIT_SUBSURFACE             1134
#define IDC_SPIN_TURB                   1135
#define IDC_SPIN_SUBSURFACE             1135
#define IDC_EDIT_GA                     1136
#define IDC_EDIT_CLEARCOAT              1136
#define IDC_SPIN_GA                     1137
#define IDC_SPIN_CLEARCOAT              1137
#define IDC_EDIT_SUN_X                  1138
#define IDC_EDIT_CC_ROUGHNESS           1138
#define IDC_SPIN_SUN_X                  1139
#define IDC_SPIN_CC_ROUGHNESS           1139
#define IDC_EDIT_SUN_Y                  1140
#define IDC_EDIT_ALPHA                  1140
#define IDC_SPIN_SUN_Y                  1141
#define IDC_SPIN_ALPHA                  1141
#define IDC_EDIT_SUN_Z                  1142
#define IDC_SPIN_SUN_Z                  1143
#define IDC_EDIT_TILE_WIDTH             1144
#define IDC_SPIN_TILE_WIDTH             1145
#define IDC_EDIT_TILE_HEIGHT            1146
#define IDC_SPIN_TILE_HEIGHT            1147
#define IDC_EDIT_SCALE                  1148
#define IDC_EDIT_MIST_EXP               1148
#define IDC_SPIN_SCALE                  1149
#define IDC_SPIN_MIST_EXP               1149
#define IDC_EDIT_RADIUS_X               1150
#define IDC_EDIT_TILE_HEIGHT_GPU        1150
#define IDC_SPIN_RADIUS_X               1151
#define IDC_SPIN_TILE_HEIGHT_CPU2       1151
#define IDC_SPIN_TILE_HEIGHT_GPU        1151
#define IDC_EDIT_RADIUS_Y               1152
#define IDC_EDIT_CPU_THREADS            1152
#define IDC_SPIN_RADIUS_Y               1153
#define IDC_SPIN_CPU_THREADS            1153
#define IDC_EDIT_RADIUS_Z               1154
#define IDC_SPIN_RADIUS_Z               1155
#define IDC_SPIN_SHARPNESS              1156
#define IDC_EDIT_SHARPNESS              1157
#define IDC_EDIT_TEX_BLUR               1158
#define IDC_SPIN_TEX_BLUR               1159
#define IDC_EDIT_DENSITY                1160
#define IDC_SPIN_DENSITY                1161
#define IDC_EDIT_ANISOTROPY             1162
#define IDC_SPIN_ANISOTROPY             1163
#define IDC_EDIT_EXPOSURE               1164
#define IDC_SPIN_EXPOSURE               1165
#define IDC_EDIT_OFFSET                 1166
#define IDC_EDIT_FILTER_SIZE            1166
#define IDC_SPIN_OFFSET                 1167
#define IDC_SPIN_FILTER_SIZE            1167
#define IDC_EDIT_ROUGHNESS_U            1168
#define IDC_SPIN_ROUGHNESS_U            1169
#define IDC_EDIT_LP_MAX_BOUNCE          1170
#define IDC_SPIN_LP_MAX_BOUNCE          1171
#define IDC_EDIT_LP_MIN_BOUNCE          1172
#define IDC_SPIN_LP_MIN_BOUNCE          1173
#define IDC_EDIT_ROUGHNESS_V            1174
#define IDC_SPIN_ROUGHNESS_V            1175
#define IDC_EDIT_LP_DIFFUSE_BOUNCE      1176
#define IDC_SPIN_LP_DIFFUSE_BOUNCE      1177
#define IDC_EDIT_LP_GLOSSY_BOUNCE       1178
#define IDC_SPIN_LP_GLOSSY_BOUNCE       1179
#define IDC_EDIT_LP_TRANS_BOUNCE        1180
#define IDC_SPIN_LP_TRANS_BOUNCE        1181
#define IDC_EDIT_BITMAP_WIDTH           1182
#define IDC_SPIN_BITMAP_WIDTH           1183
#define IDC_EDIT_LP_VOL_BOUNCE          1184
#define IDC_SPIN_LP_VOL_BOUNCE          1185
#define IDC_EDIT_BITMAP_HEIGHT          1186
#define IDC_EDIT_LP_TRANSP_BOUNCE       1186
#define IDC_SPIN_BITMAP_HEIGHT          1187
#define IDC_SPIN_LP_TRANSP_BOUNCE       1187
#define IDC_EDIT_INTENSITY_MUL          1188
#define IDC_SPIN_INTENSITY_MUL          1189
#define IDC_EDIT_MIS_MAP_SIZE           1190
#define IDC_SPIN_MIS_MAP_SIZE           1191
#define IDC_EDIT_DEFORM_BLUR_SAMPLES    1192
#define IDC_SPIN_DEFORM_BLUR_SAMPLES    1193
#define IDC_EDIT_POINT_LIGHT_SIZE       1194
#define IDC_SPIN_MIS_MAP_SIZE2          1195
#define IDC_SPIN_POINT_LIGHT_SIZE       1195
#define IDC_EDIT_CUDA_GPU               1300
#define IDC_EDIT_OPTIX_GPU              1301
#define IDC_BUTTON_TEXMAP               1400
#define IDC_BOOL_TEXMAP                 1401
#define IDC_BUTTON_MAP_ROUGH            1402
#define IDC_BOOL_MAP_ROUGH              1403
#define IDC_BUTTON_MAP_ANISO            1404
#define IDC_BOOL_MAP_ANISO              1405
#define IDC_BUTTON_MAP_COLOR            1406
#define IDC_BOOL_MAP_COLOR              1407
#define IDC_BUTTON_MAP_FAC              1408
#define IDC_BUTTON_MAP_SS_COLOR         1408
#define IDC_BOOL_MAP_FAC                1409
#define IDC_BOOL_MAP_SS_COLOR           1410
#define IDC_BUTTON_MAP_SCALE            1411
#define IDC_BOOL_MAP_SCALE              1412
#define IDC_BUTTON_MAP_SHARPNESS        1413
#define IDC_BOOL_MAP_SHARPNESS          1414
#define IDC_BUTTON_MAP_STRENGTH         1415
#define IDC_BOOL_MAP_STRENGTH           1416
#define IDC_BUTTON_MAP_ROT              1417
#define IDC_BOOL_MAP_ROT                1418
#define IDC_BUTTON_MAP_TEX_BLUR         1419
#define IDC_BOOL_MAP_TEX_BLUR           1420
#define IDC_BUTTON_MAP_SIZE             1421
#define IDC_BOOL_MAP_SIZE               1422
#define IDC_BUTTON_MAP_SMOOTH           1423
#define IDC_BOOL_MAP_SMOOTH             1424
#define IDC_BUTTON_MAP_SIGMA            1425
#define IDC_BOOL_MAP_SIGMA              1426
#define IDC_BUTTON_MAP_NORMAL           1427
#define IDC_BOOL_MAP_NORMAL             1428
#define IDC_BUTTON_MAP_REFLECTION       1429
#define IDC_BOOL_MAP_REFLECTION         1430
#define IDC_BUTTON_MAP_OFFSET           1431
#define IDC_BOOL_MAP_OFFSET             1433
#define IDC_BUTTON_MAP_ROUGHNESS_U      1434
#define IDC_BOOL_MAP_ROUGHNESS_U        1435
#define IDC_BUTTON_MAP_ROUGHNESS_V      1436
#define IDC_BOOL_MAP_ROUGHNESS_V        1437
#define IDC_BUTTON_MAP_ALPHA            1438
#define IDC_BOOL_MAP_ALPHA              1439
#define IDC_BUTTON_MAP_SPECULAR_TINT    1440
#define IDC_BOOL_MAP_SPECULAR_TINT      1441
#define IDC_BUTTON_MAP_ANISOTROPIC      1442
#define IDC_BOOL_MAP_ANISOTROPIC        1443
#define IDC_BUTTON_MAP_ANISOTROPIC_ROT  1444
#define IDC_BOOL_MAP_ANISOTROPIC_ROT    1445
#define IDC_BUTTON_MAP_SUBSURFACE       1446
#define IDC_BOOL_MAP_SUBSURFACE         1447
#define IDC_BUTTON_MAP_CLEARCOAT        1448
#define IDC_BOOL_MAP_CLEARCOAT          1449
#define IDC_BUTTON_MAP_CC_ROUGHNESS     1450
#define IDC_BOOL_MAP_CC_ROUGHNESS       1451
#define IDC_BUTTON_MAP_EMISSION         1452
#define IDC_BOOL_MAP_EMISSION           1453
#define IDC_BUTTON_MAP_TEX_01           1500
#define IDC_BOOL_MAP_TEX_01             1501
#define IDC_BUTTON_MAP_TEX_02           1502
#define IDC_BOOL_MAP_TEX_02             1503
#define IDC_BUTTON_MAP_TEX_03           1504
#define IDC_BOOL_MAP_TEX_03             1505
#define IDC_BUTTON_MAP_TEX_04           1506
#define IDC_BOOL_MAP_TEX_04             1507
#define IDC_BUTTON_MAP_TEX_05           1508
#define IDC_BOOL_MAP_TEX_05             1509
#define IDC_BUTTON_MAP_TEX_06           1510
#define IDC_BOOL_MAP_TEX_06             1511
#define IDC_BUTTON_MAP_TEX_07           1512
#define IDC_BOOL_MAP_TEX_07             1513
#define IDC_BUTTON_MAP_TEX_08           1514
#define IDC_BOOL_MAP_TEX_08             1515
#define IDC_BUTTON_MAP_TEX_09           1516
#define IDC_BOOL_MAP_TEX_09             1517
#define IDC_BUTTON_MAP_TEX_10           1518
#define IDC_BOOL_MAP_TEX_10             1519
#define IDC_BUTTON_MAP_TEX_11           1520
#define IDC_BOOL_MAP_TEX_11             1521
#define IDC_BUTTON_MAP_TEX_12           1522
#define IDC_BOOL_MAP_TEX_12             1523
#define IDC_BUTTON_MAP_TEX_13           1524
#define IDC_BOOL_MAP_TEX_13             1525
#define IDC_BUTTON_MAP_TEX_14           1526
#define IDC_BOOL_MAP_TEX_14             1527
#define IDC_BUTTON_MAP_TEX_15           1528
#define IDC_BOOL_MAP_TEX_15             1529
#define IDC_BUTTON_MAP_TEX_16           1530
#define IDC_BOOL_MAP_TEX_16             1531
#define IDC_BUTTON_MAP_TEX_17           1532
#define IDC_BOOL_MAP_TEX_17             1533
#define IDC_BUTTON_MAP_TEX_18           1534
#define IDC_BOOL_MAP_TEX_18             1535
#define IDC_BUTTON_MAP_TEX_19           1536
#define IDC_BOOL_MAP_TEX_19             1537
#define IDC_BUTTON_MAP_TEX_20           1538
#define IDC_BOOL_MAP_TEX_20             1539
#define IDC_BUTTON_MAP_TEX_21           1540
#define IDC_BOOL_MAP_TEX_21             1541
#define IDC_BUTTON_MAP_TEX_22           1542
#define IDC_BOOL_MAP_TEX_22             1543
#define IDC_BUTTON_MAP_TEX_23           1544
#define IDC_BOOL_MAP_TEX_23             1545
#define IDC_BUTTON_MAP_TEX_24           1546
#define IDC_BOOL_MAP_TEX_24             1547
#define IDC_BUTTON_MAP_TEX_25           1548
#define IDC_BOOL_MAP_TEX_25             1549
#define IDC_BUTTON_MAP_TEX_26           1550
#define IDC_BOOL_MAP_TEX_26             1551
#define IDC_BUTTON_MAP_TEX_27           1552
#define IDC_BOOL_MAP_TEX_27             1553
#define IDC_BUTTON_MAP_TEX_28           1554
#define IDC_BOOL_MAP_TEX_28             1555
#define IDC_BUTTON_MAP_TEX_29           1556
#define IDC_BOOL_MAP_TEX_29             1557
#define IDC_BUTTON_MAP_TEX_30           1558
#define IDC_BOOL_MAP_TEX_30             1559
#define IDC_BUTTON_MAP_TEX_31           1560
#define IDC_BOOL_MAP_TEX_31             1561
#define IDC_BUTTON_MAP_TEX_32           1562
#define IDC_BOOL_MAP_TEX_32             1563
#define IDC_BUTTON_MAT_A                1600
#define IDC_BUTTON_MAT_B                1601
#define IDC_BUTTON_MAT_SURFACE          1602
#define IDC_BUTTON_MAT_VIEWPORT         1603
#define IDC_BUTTON_MAT_VOLUME           1604
#define IDC_BUTTON_OPEN_NODE_EDITOR     1605
#define IDC_BUTTON_WEBSITE              1606
#define IDC_BUTTON_UPDATE_PREVIEW       1607
#define IDC_BUTTON_WEBSITE2             1607
#define IDC_BUTTON_CHECK_UPDATE         1607
#define IDC_BUTTON_GITHUB               1607
#define IDC_BUTTON_LOAD_SHADER          1608
#define IDC_BUTTON_MANUAL               1608
#define IDC_BUTTON_SAVE_SHADER          1609
#define IDC_BUTTON_CUDA_GPU_SELECT      1610
#define IDC_BUTTON_OPTIX_GPU_SELECT     1611
#define IDC_BOOL_USE_MIS                1700
#define IDC_BOOL_PROGRESSIVE_REFINE     1701
#define IDC_BOOL_TRANSPARENT_SKY        1702
#define IDC_BOOL_ENABLE_NORMAL_MAP      1703
#define IDC_BOOL_ENABLE_INVERT_GREEN    1704
#define IDC_BOOL_DEBUG_DIAGNOSTIC       1705
#define IDC_BOOL_ANIMATE_RAND_SEED      1706
#define IDC_BOOL_DEBUG_MULTI_CUDA       1706
#define IDC_BOOL_CLAMP_DIRECT           1707
#define IDC_BOOL_CLAMP_INDIRECT         1708
#define IDC_BOOL_CUDA_CPU               1709
#define IDC_RADIO_DIST_MULTI_GGX        7000
#define IDC_RADIO_DIST_AS               7001
#define IDC_RADIO_DIST_GGX              7002
#define IDC_RADIO_DIST_BECKMANN         7003
#define IDC_RADIO_DIST_SHARP            7004
#define IDC_RADIO_COMP_GLOSSY           7007
#define IDC_RADIO_COMP_DIFFUSE          7008
#define IDC_RADIO_COMP_TRANSMISSION     7009
#define IDC_RADIO_COMP_REFLECTION       7010
#define IDC_RADIO_PREC_UCHAR            7011
#define IDC_RADIO_PREC_FLOAT            7012
#define IDC_RADIO_SKY_TYPE_HW           7013
#define IDC_RADIO_SKY_TYPE_PREETHAM     7014
#define IDC_RADIO_PROJ_MB               7015
#define IDC_RADIO_PROJ_EQUIRECTANGULAR  7016
#define IDC_RADIO_PROJ_BACKPLATE        7017
#define IDC_RADIO_DEV_CPU               7018
#define IDC_RADIO_PROJ_MB_REFL          7019
#define IDC_RADIO_PROJ_EQUIRECTANGULAR_REFL 7020
#define IDC_RADIO_FALLOFF_CUBIC         7021
#define IDC_RADIO_FALLOFF_GAUSSIAN      7022
#define IDC_RADIO_FALLOFF_BURLEY        7023
#define IDC_RADIO_SPACE_TANGENT         7024
#define IDC_RADIO_FALLOFF_RANDOM_WALK   7025
#define IDC_RADIO_SPACE_OBJECT          7026
#define IDC_RADIO_SPACE_WORLD           7027
#define IDC_RADIO_DEV_CUDA              7028
#define IDC_RADIO_BLEND_NORMAL          7029
#define IDC_RADIO_BLEND_FRESNEL         7030
#define IDC_RADIO_STEREO_MODE_NONE      7031
#define IDC_RADIO_DEV_OPTIX             7032
#define IDC_RADIO_STEREO_MODE_LEFT      7033
#define IDC_RADIO_STEREO_MODE_RIGHT     7034
#define IDC_RADIO_STEREO_MODE_ANAGLYPH  7035
#define IDC_RADIO_STEREO_MODE_LR        7036
#define IDC_RADIO_STEREO_MODE_TB        7037
#define IDC_RADIO_DIST_SSS_BURLEY       7038
#define IDC_RADIO_DIST_SSS_RW           7039
#define IDD_DIALOG_CUDA_MULTI_DEVICE    8000
#define IDD_DIALOG_OPTIX_MULTI_DEVICE   8001
#define IDC_RADIO_PANO_EQUIR            9001
#define IDC_EDIT_NEARCLIP               9002
#define IDC_SPIN_NEARCLIP               9003
#define IDC_EDIT_FARCLIP                9004
#define IDC_SPIN_FARCLIP                9005
#define IDC_RADIO_CAMTYPE_EQUIRECTANGULAR 9006
#define IDC_RADIO_CAMTYPE_FE_EQUIDISTANT 9007
#define IDC_RADIO_CAMTYPE_FE_EQUISOLID  9008
#define IDC_EDIT_MIN_LAT                9009
#define IDC_SPIN_MIN_LAT                9010
#define IDC_EDIT_MIN_LONG               9011
#define IDC_SPIN_MIN_LONG               9012
#define IDC_EDIT_FOV                    9013
#define IDC_SPIN_FOV                    9014
#define IDC_EDIT_INTEROCULAR_DISTANCE   9015
#define IDC_SPIN_INTEROCULAR_DISTANCE   9016
#define IDC_EDIT_CONVERGENCE_DIST       9017
#define IDC_SPIN_CONVERGENCE_DIST       9018
#define IDC_RADIO_ANAGLYPH_RC           9019
#define IDC_RADIO_ANAGLYPH_GM           9020
#define IDC_RADIO_ANAGLYPH_YB           9021
#define IDC_BOOL_STEREO_SWAP_EYES       9022
#define IDC_BOOL_SPHERICAL_STEREO       9023
#define IDC_BOOL_POLE_MERGE             9024
#define IDC_EDIT_MERGE_BEGIN            9025
#define IDC_SPIN_MERGE_BEGIN            9026
#define IDC_EDIT_MERGE_END              9027
#define IDC_SPIN_MERGE_END              9028
#define IDC_BOOL_DEVICE_01              9029
#define IDC_BOOL_DEVICE_02              9030
#define IDC_EDIT_METALLIC               9031
#define IDC_BOOL_DEVICE_03              9032
#define IDC_SPIN_METALLIC               9033
#define IDC_BOOL_DEVICE_04              9034
#define IDC_BUTTON_MAP_METALLIC         9035
#define IDC_BOOL_DEVICE_05              9036
#define IDC_BOOL_MAP_METALLIC           9037
#define IDC_BOOL_DEVICE_06              9038
#define IDC_BOOL_PROP_SHADOW_CATCHER    9039
#define IDC_BOOL_DEVICE_07              9040
#define IDC_BOOL_DEVICE_08              9041
#define IDC_BUTTON_MAP_ROUGHNESS        9042
#define IDC_RADIO_VOL_SAMPLE_MI         9043
#define IDC_BOOL_DEVICE_09              9044
#define IDC_BOOL_MAP_ROUGHNESS          9045
#define IDC_RADIO_VOL_SAMPLE_EQUIANGULAR 9046
#define IDC_BOOL_DEVICE_10              9047
#define IDC_BUTTON_MAP_SHEEN            9048
#define IDC_RADIO_VOL_SAMPLE_DISTANCE   9049
#define IDC_BOOL_MAP_SHEEN              9050
#define IDC_RADIO_VOL_INTERP_LINEAR     9051
#define IDC_BUTTON_MAP_SHEEN_TINT       9052
#define IDC_RADIO_VOL_INTERP_CUBIC      9053
#define IDC_BOOL_MAP_SHEEN_TINT         9054
#define IDC_BOOL_VOL_HOMOGENEOUS        9055
#define IDC_BUTTON_MAP_TRANSMISSION     9056
#define IDC_EDIT_MIST_NEAR              9057
#define IDC_BOOL_MAP_TRANSMISSION       9058
#define IDC_SPIN_MIST_NEAR              9059
#define IDC_BUTTON_MAP_TRANSMISSION_ROUGHNESS 9060
#define IDC_EDIT_MIST_DEPTH             9061
#define IDC_BOOL_MAP_TRANSMISSION_ROUGHNESS 9062
#define IDC_SPIN_MIST_DEPTH             9063
#define IDC_BUTTON_MAP_SPECULAR         9064
#define IDC_BOOL_MAP_SPECULAR           9065
#define IDC_BOOL_ADAPTIVE_SAMPLING      9066
#define IDC_RADIO_FILTER_BOX            9067
#define IDC_RADIO_FILTER_GAUSSIAN       9068
#define IDC_RADIO_FILTER_BLACKMAN_HARRIS 9069
#define IDC_RADIO_DISPLACE_BUMP         9071
#define IDC_RADIO_DISPLACE_DISPLACE     9072
#define IDC_RADIO_DISPLACE_BOTH         9073

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         9072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
